Question 1 https://vceguide.com/when-trying-to-unmount-a-device-it-is-reported-as-being-busy-which-of-the-following-commands-could-be-used-to-determine-which-process-is-causing-this-2/
Question 2 https://vceguide.com/which-command-is-used-to-set-restrictions-on-the-size-of-a-core-file-that-is-created-for-a-user-when-a-program-crashes-3/
Question 3 https://vceguide.com/which-configuration-file-would-be-edited-to-change-the-default-options-for-outbound-ssh-sessions-2/
Question 4 https://vceguide.com/which-of-the-following-programs-uses-the-hosts-allow-file-to-perform-its-main-task-of-checking-for-access-control-restrictions-to-system-services-4/
Question 5 https://vceguide.com/what-file-will-temporarily-prevent-all-users-except-root-from-logging-into-the-system/
Question 6 https://vceguide.com/what-environment-variable-is-automatically-set-in-the-remote-host-shell-that-is-not-set-when-x11-forwarding-is-not-enabled/
Question 7 https://vceguide.com/which-attribute-specifies-the-network-address-that-will-be-used-to-provide-the-service-2/
Question 8 https://vceguide.com/what-argument-to-the-type-option-of-find-will-match-files-that-are-symbolic-links/
Question 9 https://vceguide.com/which-keyword-must-be-listed-in-the-hosts-option-of-the-name-service-switch-configuration-file-in-order-to-make-host-lookups-consult-the-etchosts-file-2/
Question 10 https://vceguide.com/which-of-the-following-errors-does-that-indicate-2/
Question 11 https://vceguide.com/which-of-the-following-keywords-can-be-used-in-the-file-etcresolv-conf-2/
Question 12 https://vceguide.com/which-of-the-following-is-a-valid-ipv6-address-2/
Question 13 https://vceguide.com/which-of-the-following-programs-can-be-used-to-determine-the-routing-path-to-a-given-destination-2/
Question 14 https://vceguide.com/how-would-an-outgoing-packet-to-the-destination-192-168-2-150-be-handled-2/
Question 15 https://vceguide.com/what-of-the-following-can-be-done-by-the-command-ifconfig-2/
Question 16 https://vceguide.com/which-of-the-following-tools-used-for-dns-debugging-reports-not-only-the-response-from-the-name-server-but-also-details-about-the-query-2/
Question 17 https://vceguide.com/which-of-the-following-ipv4-networks-are-reserved-by-iana-for-private-address-assignment-and-private-routing-2/
Question 18 https://vceguide.com/which-port-is-the-default-server-port-for-the-https-protocol-2/
Question 19 https://vceguide.com/which-command-depending-on-its-options-can-display-the-open-network-connections-the-routing-tables-as-well-as-network-interface-statistics-specify-only-the-command-without-any-path-or-parameters/
Question 20 https://vceguide.com/which-of-the-following-statements-is-valid-in-the-file-etcnsswitch-conf-2/
Question 21 https://vceguide.com/what-is-the-lowest-numbered-unprivileged-tcp-port-2/
Question 22 https://vceguide.com/what-is-true-regarding-tcp-port-23/
Question 23 https://vceguide.com/how-many-ip-addresses-can-be-used-for-unique-hosts-inside-the-ipv4-subnet-192-168-2-12828-2/
Question 24 https://vceguide.com/which-of-the-following-may-occur-as-a-consequence-of-using-the-command-ifconfig/
Question 25 https://vceguide.com/which-of-the-following-keywords-can-be-used-in-the-file-etcnsswitch-conf-to-specify-a-source-for-host-name-lookups/
Question 26 https://vceguide.com/which-of-the-following-lines-are-valid-in-the-file-etchosts/
Question 27 https://vceguide.com/what-is-true-regarding-a-default-route/
Question 28 https://vceguide.com/which-parameter-must-be-passed-to-ifconfig-to-activate-a-previously-inactive-network-interface/
Question 29 https://vceguide.com/which-of-the-following-is-true-about-ipv6/
Question 30 https://vceguide.com/which-command-is-used-to-set-the-hostname-of-the-local-system/
Question 31 https://vceguide.com/which-of-the-following-details-is-not-provided-in-any-output-from-the-netstat-utility/
Question 32 https://vceguide.com/which-of-the-following-commands-can-be-used-to-display-the-local-routing-table/
Question 33 https://vceguide.com/what-is-the-purpose-of-the-nsswitch-conf-file-2/
Question 34 https://vceguide.com/how-many-bits-have-been-used-for-the-interface-identifier-of-an-unicast-address/
Question 35 https://vceguide.com/which-of-the-following-commands-will-help-identify-a-broken-router-between-the-local-and-the-remote-machine/
Question 36 https://vceguide.com/what-is-the-command-to-delete-the-default-gateway-from-the-system-ip-routing-table-3/
Question 37 https://vceguide.com/what-is-true-regarding-the-file-forward-2/
Question 38 https://vceguide.com/which-of-the-following-commands-is-used-to-rotate-compress-and-mail-system-logs-2/
Question 39 https://vceguide.com/which-of-the-following-is-a-legacy-program-provided-by-cups-for-sending-files-to-the-printer-queues-on-the-command-line-2/
Question 40 https://vceguide.com/what-entry-can-be-added-to-the-syslog-conf-file-to-have-all-syslog-messages-generated-by-a-system-displayed-on-console-12-2/
Question 41 https://vceguide.com/what-is-true-about-the-ntpdate-command-2/
Question 42 https://vceguide.com/simulation-50/
Question 43 https://vceguide.com/which-command-available-with-all-mtas-is-used-to-list-the-contents-of-the-mtas-mail-queue-2/
Question 44 https://vceguide.com/which-command-is-used-to-sync-the-hardware-clock-to-the-system-clock/
Question 45 https://vceguide.com/which-of-the-following-is-observed-and-corrected-by-a-ntp-client-2/
Question 46 https://vceguide.com/which-of-the-following-are-commonly-used-mail-transfer-agent-mta-applications-3/
Question 47 https://vceguide.com/why-is-the-correct-configuration-of-a-systems-time-zone-important/
Question 48 https://vceguide.com/which-of-the-following-parameters-are-used-for-journalctl-to-limit-the-time-frame-of-the-output/
Question 49 https://vceguide.com/which-command-must-be-run-in-order-to-ensure-the-mta-knows-about-it/
Question 50 https://vceguide.com/what-is-true-regarding-the-command-sendmail/
Question 51 https://vceguide.com/which-file-inside-the-cups-configuration-directory-contains-the-definition-of-the-printers/
Question 52 https://vceguide.com/what-is-the-purpose-of-the-command-mailq/
Question 53 https://vceguide.com/which-of-the-following-are-syslog-facilities/
Question 54 https://vceguide.com/which-of-the-following-tasks-can-be-accomplished-using-the-command-date/
Question 55 https://vceguide.com/what-command-can-be-used-to-display-the-status-of-the-printers-queue/
Question 56 https://vceguide.com/which-option-in-the-etcntp-conf-file-specifies-an-external-ntp-source-to-be-queried-for-time-information/
Question 57 https://vceguide.com/which-of-the-following-fields-can-be-found-in-the-etcgroup-file-2/
Question 58 https://vceguide.com/what-is-true-regarding-the-command-userdel-force-remove-bob-2/
Question 59 https://vceguide.com/what-is-true-about-the-file-etclocaltime-2/
Question 60 https://vceguide.com/what-is-not-contained-in-the-locale-setting-of-the-operating-system-4/
Question 61 https://vceguide.com/which-command-is-used-to-add-an-empty-group-to-the-system-2/
Question 62 https://vceguide.com/which-commands-can-be-used-to-change-a-users-account-aging-information-2/
Question 63 https://vceguide.com/which-file-if-present-must-all-users-be-listed-that-are-allowed-to-use-the-cron-scheduling-system-3/
Question 64 https://vceguide.com/which-of-the-following-commands-should-be-added-to-etcbash_profile-in-order-to-change-the-language-of-messages-for-an-internationalized-program-to-portuguese-pt-2/
Question 65 https://vceguide.com/which-of-the-following-files-assigns-a-user-to-its-primary-group-2/
Question 66 https://vceguide.com/which-of-the-following-crontab-entries-will-execute-myscript-at-30-minutes-past-every-hour-on-sundays-2/
Question 67 https://vceguide.com/what-should-the-administrator-do-35/
Question 68 https://vceguide.com/what-character-2/
Question 69 https://vceguide.com/which-environment-variable-should-be-set-in-order-to-change-the-time-zone-for-the-commands-run-from-within-the-environment-variables-scope/
Question 70 https://vceguide.com/which-file-contains-the-date-of-the-last-change-of-a-users-password/
Question 71 https://vceguide.com/where-are-user-specific-crontabs-stored/
Question 72 https://vceguide.com/which-of-the-following-commands-can-remove-a-user-from-a-group/
Question 73 https://vceguide.com/which-of-the-following-is-true-19/
Question 74 https://vceguide.com/what-is-the-purpose-of-the-iconv-command/
Question 75 https://vceguide.com/which-command-can-be-used-to-delete-a-group-from-a-linux-system/
Question 76 https://vceguide.com/which-of-the-following-fields-are-available-in-both-the-global-etccrontab-file-as-well-as-in-user-specific-crontab-files/
Question 77 https://vceguide.com/which-directory-2/
Question 78 https://vceguide.com/which-file-specifies-the-user-accounts-that-can-not-submit-jobs-via-at-or-batch-2/
Question 79 https://vceguide.com/which-character-in-the-password-field-of-etcpasswd-is-used-to-indicate-that-the-encrypted-password-is-stored-in-etcshadow-2/
Question 80 https://vceguide.com/which-of-the-following-steps-prevents-a-user-from-obtaining-an-interactive-login-session/
Question 81 https://vceguide.com/which-of-the-following-are-tasks-handled-by-a-display-manager-like-xdm-or-kdm-2/
Question 82 https://vceguide.com/what-is-the-name-of-the-simple-graphical-login-manager-that-comes-with-a-vanilla-x11-installation-3/
Question 83 https://vceguide.com/which-of-the-following-programs-is-an-on-screen-keyboard-4/
Question 84 https://vceguide.com/what-is-the-default-name-of-the-configuration-file-for-the-xorg-x11-server-2/
Question 85 https://vceguide.com/which-of-the-following-commands-shows-the-current-color-depth-of-the-x-server-2/
Question 86 https://vceguide.com/what-is-the-purpose-of-a-screen-reader/
Question 87 https://vceguide.com/how-is-a-display-manager-started-2/
Question 88 https://vceguide.com/which-command-can-be-used-to-investigate-the-properties-for-a-particular-window-in-x-by-clicking-that-window/
Question 89 https://vceguide.com/how-is-the-content-of-the-section-sectionname-associated-with-that-section/
Question 90 https://vceguide.com/which-file-used-by-xdm-specifies-the-default-wallpaper/
Question 91 https://vceguide.com/which-of-the-following-are-requirements-in-order-to-run-a-shell-script-like-a-regular-command-from-anywhere-in-the-filesystem/
Question 92 https://vceguide.com/what-command-displays-all-aliases-defined-in-the-current-shell/
Question 93 https://vceguide.com/what-is-the-purpose-of-the-file-etcprofile/
Question 94 https://vceguide.com/which-of-the-following-sql-queries-counts-the-number-of-occurrences-for-each-value-of-the-field-order_type-in-the-table-orders/
Question 95 https://vceguide.com/which-of-the-following-commands-lists-all-defined-variables-and-functions-within-bash/
Question 96 https://vceguide.com/which-of-the-following-words-is-used-to-restrict-the-records-that-are-returned-from-a-select-sql-query-based-on-a-supplied-criteria-for-the-values-in-the-records/
Question 97 https://vceguide.com/what-output-will-the-following-command-produce-2/
Question 98 https://vceguide.com/when-the-command-echo-outputs-12942-what-is-the-meaning-of-12942/
Question 99 https://vceguide.com/how-can-the-existing-environment-variable-foobar-be-suppressed-for-the-execution-of-the-script-myscript-only/
Question 100 https://vceguide.com/what-is-the-difference-between-the-commands-test-e-path-and-test-f-path/
Question 101 https://vceguide.com/which-of-the-following-files-when-existing-affect-the-behavior-of-the-bash-shell-2/
Question 102 https://vceguide.com/which-of-the-following-commands-puts-the-output-of-the-command-date-into-the-shell-variable-mydate-2/
Question 103 https://vceguide.com/produce-2/
Question 104 https://vceguide.com/which-directory-will-be-copied-to-a-new-users-home-directory-when-the-account-is-created-by-passing-the-m-option-to-the-useradd-command-3/
Question 105 https://vceguide.com/what-word-is-missing-from-the-following-sql-statement-9/
Question 106 https://vceguide.com/what-output-will-the-command-seq-10-produce-3/
Question 107 https://vceguide.com/which-command-makes-the-shell-variable-named-variable-visible-to-subshells-2/
Question 108 https://vceguide.com/what-word-is-missing-from-the-following-sql-statement-8/
Question 109 https://vceguide.com/when-the-command-echo-outputs-1-which-of-the-following-statements-is-true/
Question 110 https://vceguide.com/what-output-will-the-following-command-sequence-produce-4/
